version: '2'
services:
  digital-text-forensics:
    image: '43ndr1k/digital-text-forensics:latest'
    build: .
    restart: always
    ports:
      - '127.0.0.1:8088:8080'
    volumes:
      - 'spring_digital_text_forensics_pdfs:/pdfDocs'
      - 'spring_digital_text_forensics_db:/root/h2'
volumes:
  spring_digital_text_forensics_pdfs:
    driver: local
  spring_digital_text_forensics_db:
      driver: local
      # speicherort: /var/lib/docker/volumes
      # sudo docker cp pdfDocs/ docker_digital-text-forensics_1:.

