version: '2'
services:
  digital-text-forensics:
    image: '43ndr1k/digital-text-forensics:latest'
    build: .
    restart: always
    ports:
      - '127.0.0.1:8088:8080'

    volumes:
      - './pdfDocs:/pdfDocs'
      - './xmlFiles:/xmlFiles'
      - './h2:/root/h2'
      - './LuceneIndex:/LuceneIndex'
      - './upload-dir:/upload-dir'


volumes:
  digital-text-forensics:

      # speicherort: /var/lib/docker/volumes
      # sudo docker cp pdfDocs/ docker_digital-text-forensics_1:.
      # sudo docker cp ../LuceneIndex/ docker_digital-text-forensics_1:LuceneIndex/
      # sudo docker cp ../pdfDocs/ docker_digital-text-forensics_1:pdfDocs/
      # sudo docker cp ../xmlFiles/ docker_digital-text-forensics_1:xmlFiles/


